### ISSUE TITLE
Fatal error: Class 'Token' not found in /usr/local/symfony/plugins/sfMelodyPlugin/lib/user/sfMelodyUser.class.php on line 165

### ISSUE THREAD

**Issue by savannahbeckett** [chok/sfMelodyPlugin#10]
I keep getting this fatal error: Fatal error: Class 'Token' not found in /usr/local/symfony/plugins/sfMelodyPlugin/lib/user/sfMelodyUser.class.php on line 165, why?  

I try to connect to gmail to retrieve all emails in contact list.  I don't have the api key, so I plan to use anonymous for both key and secret for now.  Would you post setting and code examples of how to do that?  I tried to use your facebook example, but I get this fatal error for class token.
Thanks.

**Comment by savannahbeckett** [comment]
I think Token class maybe from model?  My site currently has no model because there is no DB access so far.  So I didn't rebuild any model or DB when I install this plugin.  Can this plugin work without model?
Thanks.

**Comment by chok** [comment]
Huum. If a user isn't authenticated if you have specified create-user: false. I think It could be work without model.

But did you install sfDoctrineOAuthPlugin ? You need it to use OAuth for this plugin.

**Comment by savannahbeckett** [comment]
I already installed 2 additional plugins for Doctrine as instructed.  I couldn't find class Token in sfDoctrineOAuthPlugin, but I found it in 
lib/vendor/symfony/lib/plugins/sfPropelPlugin/lib/vendor/phing/filters/ReplaceTokens.php, is it the one?  Is class Token originated from sfDoctrineOAuth plugin?  Would you give example of how to connect to google contact like the way to did for facebook?  Thanks.

**Comment by savannahbeckett** [comment]
What version of sfDoctrineOAuthPlugin does sfMelodyPlugin support?  It seems that sfDoctrineOAuthPlugin may have changed the class name Token to PluginToken?.  I am using sfDoctrineOAuthPlugin 1.1.2.

**Comment by chok** [comment]
I'll try to post some example later.

In fact you have to build the model to have the token class. 

./symfony doctrine:build --all-classes. You can launch this without any connection to database.

There is no link with ReplaceTokens of Propel and the Token Class of sfDoctrineOAuth.

By specifying create-user: false, it doesn't work ?

**Comment by savannahbeckett** [comment]
yes, I set create-user to false.  Now, google gave me Invalid Token error.  I run only  $this->getUser()->connect('google').  Keep in mind that I haven't register my domain with google, but I should be able to use "anonymous" based on my research.

Following is my setting:

all:
  melody:
    create_user: false  
    redirect_register: false                                        

```
google:
  key:  anonymous
  secret: anonymous
  callback: myindex   # or absolute url

  #needed for google or facebook
  api: [contacts]        # only for google - easy way to set scopes
  scope: [permission_1]  

  provider: google

  namespaces:                 
    contacts: http://www.google.com/m8/feeds/

  output_format: json
```

**Comment by chok** [comment]
try this :

```
all:
  melody:
    create-user: false
    google:
      key: anonymous
      secret: anonymous
      callback: "@myindex"
      api:   [contacts]
```
