### ISSUE TITLE
Redirection loop

### ISSUE THREAD

**Issue by tobiassjosten** [chok/sfMelodyPlugin#20]
I am trying to set up a Facebook connection with sfMelodyPlugin and it looks pretty good so far. My user is created and its profile fields are populated properly. But I keep getting into a redirection loop on /access/facebook.

After lurking around in the code I'm suspecting I might have forgotten some 'callback' configuration, but I can't find anything on this in the documentation. What do you think could cause this?

**Comment by chok** [comment]
Can you post your config ?

**Comment by tobiassjosten** [comment]
Of course. Here's what I can think of. Let me know if you need anything else to try and figure it out. Thanks!

I am using the sample connect action to do my Facebook authentication. And this creates a user with proper data just fine, it just then enters a redirection loop, where /access/facebook redirects with 302 to itself.

Oh, and as you can see there are some remnants left of sfFacebookConnectPlugin. I'm replacing it with sfMelodyPlugin but I don't think this should cause a conflict.

app.yml

```
melody:
  create_user: true

  facebook:
    key: myfacebookkey
    secret: myfacebooksecret
    scope:
      - email
      - offline_access
    user:
      username:
        call: me
        path: id
        prefix: Facebook_
      first_name:
        call: me
        path: first_name
      last_name: 
        call: me
        path: last_name
      email_address:               
        call: me                  
        path: email               
        key: true
```

settings.yml

```
enabled_modules:
  - default
  - sfFacebookConnectAuth
  - sfGuardAuth
  - sfMelody
```

schema.yml

```
sfGuardUser:
  columns:
    username:
      type: string(128)
      unique: false
sfGuardUserProfile:
  columns:
    user_id: integer(5)
    first_name: varchar(64)
    last_name: varchar(64)
    facebook_uid: integer(5)
  relations:
    sfGuardUser:
      type: one
      foreignType: one
      class: sfGuardUser
      local: user_id
      foreign: id
      onDelete: cascade
      foreignAlias: Profile
```

myUser.class.php

```
class myUser extends sfMelodyUser
{
}
```

ProjectConfiguration.class.php

```
class ProjectConfiguration extends sfProjectConfiguration
{
  public function setup()
  {
    $this->enablePlugins(
      'sfDoctrinePlugin',
      'sfDoctrineGuardPlugin',
      'sfDoctrineOAuthPlugin',
      'sfFacebookConnectPlugin',
      'sfMelodyPlugin',
      'sfScraperPlugin'
    );
  }
}
```

**Comment by chok** [comment]
In your app.yml, you have to put a callback to redirect wher you want :

```
melody:
  create_user: true
  facebook:
    callback: @mymodule_index 
    ...
```

This solution fix your problem ?
