### ISSUE TITLE
Issue retrieving contact details from Google

### ISSUE THREAD

**Issue by plushgraffiti** [chok/sfMelodyPlugin#21]
I am able to get the email address (id) via this:

```
email_address:               
      key: true
      call: contacts/me
      path: feed.id.$t
```

but not the users name via this:

```
first_name:
      key: true
      call: contacts/me
      path: feed.author.name.$t
```

Any idea why?

**Comment by plushgraffiti** [comment]
Managed to find out how to do this: author was an array, accessible by:

```
path: feed.author.0.name.$t
```

**Comment by chok** [comment]
Yes, I've just found this

```
  username:
      call: contacts/me
      path: feed.author.0.name.$t
      prefix: Google_
```

Too late...
