### ISSUE TITLE
Using sfMelody to connect to Twitter as a single user

### ISSUE THREAD

**Issue by sglessard** [chok/sfMelodyPlugin#36]
Hello,

I was using curl to get tweets from a single user (some company) to print on some website. I recently installed sfMelody to use OAuth. I don't figure out how to use "Access token" and "Access token secret" in app.yml. I tried some lines, like :

``` yml
twitter:
  key:  <string>
  secret: <string>

  user:
    screen_name: someuser
    oauth_token: <string>
    oauth_token_secret: <string>
```

or 

``` yml
  auth_parameters:
    oauth_token: <string>
    oauth_token_secret: <string>
```

Is there a way to use Twitter/sfMelody with a predefined user, without any access-url redirection?
