### ISSUE TITLE
Trying to authenticate users through twitter and google... no success!

### ISSUE THREAD

**Issue by edse** [chok/sfMelodyPlugin#37]
I'm trying to use sfMelodyPlugin to authentificate users through facebook, twitter and google.

For facebook it works as a charm. But for twitter and google I can't make it work...

app.yml:

all:
  melody:
    create_user: true
    facebook:
      key: XXX
      secret: XXX
      callback: @facebook_callback
      provider: facebook
      scope: [email]

```
  user:
    username:
      call: me 
      path: id
      prefix: facebook_
    first_name:
      call: me
      path: first_name
    last_name: 
      call: me
      path: last_name
    email_address:               
      call: me                  
      path: email               
      key: true

twitter:
  key:  XXX
  secret: XXX
  callback: @twitter_callback

  user:
    username:
      call: me
      path: id
      prefix: twitter_
    first_name:
      call: me
      path: first_name
    last_name: 
      call: me
      path: last_name
    email_address:               
      call: me                  
      path: email               
      key: true

  provider: twitter
  request_token_url: https://api.twitter.com/oauth/request_token
  request_auth_url: https://api.twitter.com/oauth/authorize
  access_token_url: https://api.twitter.com/oauth/access_token

  auth_parameters:
    param1: value
  call_parameters:
    param1: value
  access_parameters:
    param1: value
  output_format: json
  create_user: true
  redirect_register: false

  #optional only for OAuth 1
  request_parameters:
    param1: value
  request_token_url: https://api.twitter.com/oauth/request_token 

google:
  key: XXX
  secret: XXX
  callback: @google_callback
  provider: google
```
1. When I try to connect with twitter it redirect to "https://api.twitter.com/oauth/authorize?param1=value" (no token here!?!?!?) with the message: 

Woah there!

This page requires some information that was not provided. Please return to the site that sent you to this page and try again

Here is the log for the action listed above:

Jul 25 16:58:19 symfony [info] {sfPatternRouting} Match route "twitter_connect" (/login/twitter) for /login/twitter with parameters array (  'module' => 'login',  'action' => 'twitterConnect',)
Jul 25 16:58:19 symfony [info] {sfFilterChain} Executing filter "sfRenderingFilter"
Jul 25 16:58:19 symfony [info] {sfFilterChain} Executing filter "sfExecutionFilter"
Jul 25 16:58:19 symfony [info] {loginActions} Call "loginActions->executeTwitterConnect()"
Jul 25 16:58:19 symfony [info] {OAuth} call https://api.twitter.com/oauth/request_token with params oauth_callback=http%3A%2F%2Fwww.mysite.com%2Ftests%2F01%2Fanima%2Fweb%2Ffrontend_dev.php%2Faccess%2Ftwitter&oauth_consumer_key=XXX&oauth_nonce=e5c6b010f57d78903321fa60c3428dd0&oauth_signature=ZtbcKubjPOv2MYxZMI1UCcBHri0%3D&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1311623899&oauth_version=1.0&param1=value | 
Jul 25 16:58:20 symfony [err] {OAuth} access token failed - twitter returns Array
(
    [<?xml version] => "1.0" encoding="UTF-8"?>
<hash>
  <error>Desktop applications only support the oauth_callback value 'oob'</error>
  <request>/oauth/request_token</request>
</hash>

)

Jul 25 16:58:21 symfony [info] {OAuth} "twitter" call url "https://api.twitter.com/oauth/authorize" with params "array (
  'param1' => 'value',
  'oauth_token' => NULL,
)"
Jul 25 16:58:21 symfony [info] {sfFrontWebController} Redirect to "https://api.twitter.com/oauth/authorize?param1=value"
Jul 25 16:58:21 symfony [info] {sfWebResponse} Send status "HTTP/1.1 302 Found"
Jul 25 16:58:21 symfony [info] {sfWebResponse} Send header "Location: https://api.twitter.com/oauth/authorize?param1=value"
Jul 25 16:58:21 symfony [info] {sfWebResponse} Send header "Content-Type: text/html; charset=utf-8"
Jul 25 16:58:21 symfony [info] {sfWebDebugLogger} Configuration 1.19 ms (8)
Jul 25 16:58:21 symfony [info] {sfWebDebugLogger} Factories 53.66 ms (1)
Jul 25 16:58:21 symfony [info] {sfWebDebugLogger} Action "login/twitterConnect" 1665.28 ms (1)
Jul 25 16:58:21 symfony [info] {sfWebResponse} Send content (123 o)
Jul 25 16:58:21 symfony [warning] {sfWebDebugLogger}  Warning at /home/sites/mysite/tests/01/anima/lib/vendor/symfony/lib/exception/sfException.class.php on line 105 (Cannot modify header information - headers already sent by (output started at /home/sites/mysite/tests/01/anima/lib/vendor/symfony/lib/response/sfResponse.class.php:105))
Jul 25 16:58:21 symfony [err] {sfRenderException} The template "twitterConnectSuccess.php" does not exist or is unreadable in "".
Jul 25 16:58:21 symfony [warning] {sfWebDebugLogger}  Warning at /home/sites/mysite/tests/01/anima/lib/vendor/symfony/lib/exception/sfException.class.php on line 159 (Cannot modify header information - headers already sent by (output started at /home/sites/mysite/tests/01/anima/lib/vendor/symfony/lib/response/sfResponse.class.php:105))
Jul 25 16:58:21 symfony [warning] {sfWebDebugLogger}  Warning at /home/sites/mysite/tests/01/anima/lib/vendor/symfony/lib/exception/sfException.class.php on line 159 (Cannot modify header information - headers already sent by (output started at /home/sites/mysite/tests/01/anima/lib/vendor/symfony/lib/response/sfResponse.class.php:105))
Jul 25 16:58:21 symfony [info] {sfWebDebugLogger} Configuration 1.37 ms (9)
Jul 25 16:58:21 symfony [info] {sfWebDebugLogger} Factories 53.66 ms (1)
Jul 25 16:58:21 symfony [info] {sfWebDebugLogger} Action "login/twitterConnect" 3330.94 ms (2)
Jul 25 16:58:21 symfony [info] {sfWebDebugLogger} View "Success" for "login/twitterConnect" 137.16 ms (1)
1. When i try to connect using google it redirect me to: "https://www.google.com/accounts/OAuthAuthorizeToken?" (no token here!?!?!?) with the message: Invalid Token.

Here is the log for the action listed above:

Jul 25 17:09:58 symfony [info] {sfPatternRouting} Match route "google_connect" (/login/google) for /login/google with parameters array (  'module' => 'login',  'action' => 'googleConnect',)
Jul 25 17:09:58 symfony [info] {sfFilterChain} Executing filter "sfRenderingFilter"
Jul 25 17:09:58 symfony [info] {sfFilterChain} Executing filter "sfExecutionFilter"
Jul 25 17:09:58 symfony [info] {loginActions} Call "loginActions->executeGoogleConnect()"
Jul 25 17:09:58 symfony [info] {OAuth} call https://www.google.com/accounts/OAuthGetRequestToken with params oauth_callback=http%3A%2F%2Fwww.mysite.com%2Ftests%2F01%2Fanima%2Fweb%2Ffrontend_dev.php%2Faccess%2Fgoogle&oauth_consumer_key=XXX&oauth_nonce=cd6d54dd3774d7b5afdd79d5c0182203&oauth_signature=A91LJbvkV2NKJ4IWAlpFx7F3tpY%3D&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1311624598&oauth_version=1.0 | 
Jul 25 17:09:58 symfony [err] {OAuth} access token failed - google returns Array
(
    [parameter_absent
oauth_parameters_absent:scope

] => 
)

Jul 25 17:09:58 symfony [info] {OAuth} "google" call url "https://www.google.com/accounts/OAuthAuthorizeToken" with params "array (
  'oauth_token' => NULL,
)"
Jul 25 17:09:58 symfony [info] {sfFrontWebController} Redirect to "https://www.google.com/accounts/OAuthAuthorizeToken?"
Jul 25 17:09:58 symfony [info] {sfWebResponse} Send status "HTTP/1.1 302 Found"
Jul 25 17:09:58 symfony [info] {sfWebResponse} Send header "Location: https://www.google.com/accounts/OAuthAuthorizeToken?"
Jul 25 17:09:58 symfony [info] {sfWebResponse} Send header "Content-Type: text/html; charset=utf-8"
Jul 25 17:09:58 symfony [info] {sfWebDebugLogger} Configuration 1.16 ms (8)
Jul 25 17:09:58 symfony [info] {sfWebDebugLogger} Factories 52.83 ms (1)
Jul 25 17:09:58 symfony [info] {sfWebDebugLogger} Action "login/googleConnect" 120.65 ms (1)
Jul 25 17:09:58 symfony [info] {sfWebResponse} Send content (123 o)
Jul 25 17:09:58 symfony [warning] {sfWebDebugLogger}  Warning at /home/sites/mysite/tests/01/anima/lib/vendor/symfony/lib/exception/sfException.class.php on line 105 (Cannot modify header information - headers already sent by (output started at /home/sites/mysite/tests/01/anima/lib/vendor/symfony/lib/response/sfResponse.class.php:105))
Jul 25 17:09:58 symfony [err] {sfRenderException} The template "googleConnectSuccess.php" does not exist or is unreadable in "".
Jul 25 17:09:58 symfony [warning] {sfWebDebugLogger}  Warning at /home/sites/mysite/tests/01/anima/lib/vendor/symfony/lib/exception/sfException.class.php on line 159 (Cannot modify header information - headers already sent by (output started at /home/sites/mysite/tests/01/anima/lib/vendor/symfony/lib/response/sfResponse.class.php:105))
Jul 25 17:09:58 symfony [warning] {sfWebDebugLogger}  Warning at /home/sites/mysite/tests/01/anima/lib/vendor/symfony/lib/exception/sfException.class.php on line 159 (Cannot modify header information - headers already sent by (output started at /home/sites/mysite/tests/01/anima/lib/vendor/symfony/lib/response/sfResponse.class.php:105))
Jul 25 17:09:58 symfony [info] {sfWebDebugLogger} Configuration 1.34 ms (9)
Jul 25 17:09:58 symfony [info] {sfWebDebugLogger} Factories 52.83 ms (1)
Jul 25 17:09:58 symfony [info] {sfWebDebugLogger} Action "login/googleConnect" 241.66 ms (2)
Jul 25 17:09:58 symfony [info] {sfWebDebugLogger} View "Success" for "login/googleConnect" 40.74 ms (1)

Any help will be appreciated.

Thanks,

Emerson
