### ISSUE TITLE
Problem with authentification and Inscription

### ISSUE THREAD

**Issue by Khalezis** [chok/sfMelodyPlugin#43]
Hi every one.

I have a problem with the Facebook Connect. Indeed, when i login into Facebook the plugin insert in my database a line with a blank to username's row and email's row.

here is my file routing.yml:

homepage:
  url:   /
  param: { module: main, action: index }

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_forgot_password:
  url:   /forgot_password
  param: { module: sfGuardForgotPassword, action: index }

sf_guard_register:
  url:   /register
  param: { module: sfGuardRegister, action: index }

change_language:
  url:   /change_language
  param: { module: main, action: changeLanguage }

localized_homepage:
  url:   /:sf_culture/
  param: { module: main, action: index }
  requirements:
    sf_culture: (?:fr|en)

melody_connect:
  url:   /api
  param: { module: api, action: connect }

melody_facebook:
  url: /facebook
  param: { module: api, action: facebook }

melody_facebook_feed:
  url: /facebook-feed
  param: { module: api, action: facebookFeed }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*

I have 3 modules:
- api
- main
  -sfGuard

Do you have an idea for solve this problem?

**Comment by chok** [comment]
Hi,

Sorry for the wait !

What say your logs ?

**Comment by Khalezis** [comment]
In fact, i have no error. But it's don't working. Indeed, I have a neww user with a email NULL and no Username. In the token table, I have a new entry but no new token. In conclusion, my sf_guard_user is like this:

id  first_name  last_name   email_address   username    algorithm   salt    password    is_active   is_super_admin  last_login  created_at  updated_at
            1   NULL    NULL            sha1    NULL    NULL    1   0   2011-12-20 00:30:41 2011-12-20 00:30:41 2011-12-20 00:30:41

table token:

id  name    token_key   token_secret    user_id expire  params  identifier  status  o_auth_version  created_at  updated_at
            1   facebook    NULL    NULL    1   NULL    NULL    NULL    access  2   2011-12-20 00:30:41 2011-12-20 00:30:41

my action.class.php:

``` php

<?php

 public function executeIndex(sfWebRequest $request)
  {
    $this->forward('default', 'module');
  }
  public function executeConnect(sfWebRequest $request)
  {
    $this->getUser()->connect('twitter');
        #or $this->getUser()->connect('facebook')
  }

  public function executeFacebook(sfWebRequest $request)
  {
    $fb_melody = $this->getUser()->getMelody('facebook');

    $this->me = $fb_melody->getMe(null, array('fields' => 'picture', 'size' => 'large'));
    $this->friends = $fb_melody->getFriends();

    $this->form = new FeedForm();
  }
  public function executeTwitter(sfWebRequest $request)
  {
    $fb_melody = $this->getUser()->getMelody('twitter');

    $this->me = $fb_melody->getMe();
  }

```

It's don't working with twitter or facebook.

**Comment by chok** [comment]
and your config in app.yml ?

**Comment by Khalezis** [comment]
Sorry:

``` yaml
all:
  lang:
   default: fr
  sf_guard_plugin:
   profile_class:      sfGuardUserProfile
   profile_field_name: user_id
  melody:
    create_user: true               # to create a user for all melodies 
    facebook:
      key: 202#######
      secret: #####72a00da053e9
      callback: @api_facebook
      scope: [email]                #optionnal - http://developers.facebook.com/docs/authentication/permissions
                                    # needed to create an user based on his email_address
      user:
        username:                   # the name of a field of sfGuardUser
          call: me                  # api call
          path: id                  # path could be user.object.email for example to retrieve the right inforamtion
          prefix: Facebook_
        first_name:
          call: me
          path: first_name
        last_name: 
          call: me
          path: last_name
        email_address:               
          call: me                  
          path: email               
          key: true
    twitter:
     key: DsYlu#####
     secret: ####33mRhwNXM
     callback: @api_twitter
```

routing.yml:

``` yaml
homepage:
  url:   /
  param: { module: main, action: index }

sf_guard_signin:
  url:   /login
  param: { module: User, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: User, action: signout }

sf_guard_forgot_password:
  url:   /forgot_password
  param: { module: User, action: ForgotPassword }

sf_guard_register:
  url:   /register
  param: { module: User, action: Register }

api_facebook:
  url:   /api/facebook
  param: { module: api, action: facebook }

api_twitter:
  url:   /api/facebook
  param: { module: api, action: twitter }

api_connect:
  url:   /api/connect
  param: { module: api, action: connect }

melody_facebook_feed:
  url: /facebook-feed
  param: { module: api, action: facebookFeed }

change_language:
  url:   /change_language
  param: { module: main, action: changeLanguage }

localized_homepage:
  url:   /:sf_culture/
  param: { module: main, action: index }
  requirements:
    sf_culture: (?:fr|en)

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
```
