### ISSUE TITLE
OAuth failure with Twitter

### ISSUE THREAD

**Issue by mbrung** [chok/sfMelodyPlugin#8]
Hi !

I seem to be having difficulties in authenticating with Twitter.  While the FB authentication works like a charm, Twitter auth fails upon callback.

After the user allows my app to access his/her info, Twitter calls us back with the following URL:

access/twitter?oauth_token=7WejrvRcKrUQxF16QAhb525O128146CTTA1K5tW4&oauth_verifier=hzOEQWtg34tPr4YG8NMRm1Y6GNDKYBishrK88aE

Seems legit so far.

Calling this URL fails, and I see this message in my log:

Sep 22 12:33:33 symfony [err] {OAuth} access token failed -  returns Array
(
    [ ] => 
)

I'm a bit at a loss here -- I'm sure someone else got this to work, so I wonder if perhaps I have some configuration problem.

Would you have any suggestions/ideas?

FYI the _twitter_ section in my app.yml looks like:

```
twitter:
  provider: twitter
  key: <REMOVED>
  secret: <REMOVED>
  callback: @homepage_twitter
  scope: [email]

  user:
    username:               
      call: me         
      path: id                
      prefix: "Twitter_"
    first_name:
      call: me
      path: first_name
    last_name: 
      call: me
      path: last_name
    email_address:               
      call: me                  
      path: email               
      key: true
```

**Comment by chok** [comment]
There is no scope with twitter. And You can't retrieve the email of the user.

me is an alias to call :this : http://dev.twitter.com/doc/get/users/show

As you can see in the example, there is no first_name, last_name or email_address.

**Comment by mbrung** [comment]
Thanks.

So I stripped down the twitter section in my app.yml:

```
twitter:
  provider: twitter
  key: <REMOVED>
  secret: <REMOVED>
  callback: @homepage_twitter

  user:
    username:            
      call: me          
      path: id     
      prefix: "Twitter_"
      key: true
```

Unfortunately I get the same result:

  Sep 22 13:16:15 symfony [info] {sfMelodyActions} Call "sfMelodyActions>executeAccess()"
  Sep 22 13:16:16 symfony [err] {OAuth} access token failed -  returns Array
  (
      [ ] => 
  )
