### ISSUE TITLE
Example to get Gmail contacts

### ISSUE THREAD

**Issue by stylomylo** [chok/sfMelodyPlugin#9]
Hey there,

I have a fresh symfony 1.4.8 installed and installed the doctrine and melody plugins.
I want to get the list of gmail contacts for a user that is logged in to my app.

My settings are:
 melody:
    google:
      key:                  xxx
      secret:               xxx
      callback:             @mymodule # or absolute url

```
  scope: contacts

  user:
    email_adress:
      call: me
      path: email
      key: true
```

this is in my template:
echo link_to('Connect to Gmail', '@gmailConnect')

and this in the according action:
public function executeConnect(sfWebRequest $request)
    {
      echo 'test';
      $this->getUser()->connect('google');
    }

  public function executeGoogle(sfWebRequest $request)
    {
      $this->me = $this->getUser()->getMelody('google')->getMe();
    }

When I click the link it redirects me to:
https://www.google.com/accounts/OAuthAuthorizeToken?

and on the Google page it says:
Invalid Token. 

I am new to symfony and didn't completely understand the whole concept of this plugin and the necessary steps. Could please someone help my and provide an example or explain further?

Thanks a lot.

**Comment by chok** [comment]
Use api instead of scope with Google :

```
  key: xxx
  secret: xxx
  api: [contacts]
  callback: "@my_route"
  user:
    email_address:
      key: true
      call: contacts/me
      path: feed.id.$t
```

This is solve your problems ?
